/**
 * Browserless execution of the production visual-component registry.
 *
 * The corpus is generated by tests/frontend_suite.py from real, forced student-path
 * obligations.  This file never invents payloads and never starts Vite or a browser.
 * jsdom is used only to inspect renderToStaticMarkup output; pointer geometry remains
 * explicitly outside this check because jsdom has no layout engine.
 */
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, test } from 'vitest';

import { assertVisualEvidence, renderVisualEvidence } from './staticRenderEvidence.jsx';

const corpusPath = process.env.PGEN_STATIC_RENDER_CORPUS;
const resultPath = process.env.PGEN_STATIC_RENDER_RESULT;

if (!corpusPath || !resultPath) {
  throw new Error(
    'PGEN_STATIC_RENDER_CORPUS and PGEN_STATIC_RENDER_RESULT are required; ' +
    'run PYTHONPATH=. .venv/bin/python tests/frontend_suite.py',
  );
}

const corpus = JSON.parse(fs.readFileSync(corpusPath, 'utf8'));
const outcomes = [];

function renderCase(sample, disabled) {
  const evidence = renderVisualEvidence(sample, disabled);
  expect(assertVisualEvidence(sample, evidence)).toEqual([]);
  return { markup_bytes: evidence.markup_bytes, description: evidence.description };
}

describe('production visual static rendering', () => {
  test.each(corpus.cases)('$case_id executes and is non-degenerate', (sample) => {
    const active = renderCase(sample, false);
    const disabled = renderCase(sample, true);
    outcomes.push({
      case_id: sample.case_id,
      visual_type: sample.visual_type,
      formatter: sample.formatter,
      node_id: sample.node_id,
      seed: sample.seed,
      active,
      disabled,
    });
  });

  test('writes one complete result for the digest-bound Python consumer', () => {
    expect(outcomes).toHaveLength(corpus.cases.length);
    const visualTypes = [...new Set(outcomes.map((o) => o.visual_type))].sort();
    expect(visualTypes).toEqual([...corpus.production_visual_types].sort());
    fs.mkdirSync(path.dirname(resultPath), { recursive: true });
    fs.writeFileSync(resultPath, JSON.stringify({
      schema_version: 1,
      assertion: 'frontend_static_render_12',
      cases_executed: outcomes.length,
      production_visual_types: visualTypes,
      outcomes,
      limitations: [
        'jsdom has no layout engine: NumberLine and BarChart pointer-drag geometry is unproven',
        'static markup cannot prove crowding, overlap, colour contrast, or touch-target size',
      ],
    }, null, 2) + '\n');
  });
});
