"""
Textual Formatter — Cloze (Fill-in-the-Blank)

Unified formatter for fill-in-the-blank problems.
Respects the 'context' variant:
  - "pure": Shows equation "5 + 3 = ___"
  - "word_problem": Shows story with blank "Maria has 5 apples... She has ___ apples."

For arithmetic: "5 + 3 = ___" or "___ + 3 = 8" (pure)
For word problems: Uses spine-generated text with blank inserted
"""

import random

from backend.app.practice_gen.dna.base import FormattedProblem, QuestionContext


def _build_equation_sentence(ctx: QuestionContext) -> str:
    """Build pure equation with blank based on concept and blank_target."""
    values = ctx.values
    concept = ctx.dna_concept
    blank_target = ctx.blank_target or "result"
    
    if concept == "addition":
        a = values.get("a")
        b = values.get("b")
        result = values.get("result")
        if blank_target == "result":
            return f"{a} + {b} = ___"
        elif blank_target == "b":
            return f"{a} + ___ = {result}"
        else:  # blank_target == "a"
            return f"___ + {b} = {result}"
    
    elif concept == "subtraction":
        a = values.get("a")
        b = values.get("b")
        result = values.get("result")
        if blank_target == "result":
            return f"{a} − {b} = ___"
        elif blank_target == "b":
            return f"{a} − ___ = {result}"
        else:
            return f"___ − {b} = {result}"
    
    elif concept == "multiplication":
        a = values.get("a", values.get("groups"))
        b = values.get("b", values.get("n"))
        result = values.get("result", values.get("total"))
        if blank_target in ("result", "total"):
            return f"{a} × {b} = ___"
        elif blank_target in ("b", "n"):
            return f"{a} × ___ = {result}"
        else:
            return f"___ × {b} = {result}"
    
    elif concept == "division":
        dividend = values.get("dividend", values.get("a"))
        divisor = values.get("divisor", values.get("b"))
        quotient = values.get("quotient", values.get("result"))
        if blank_target in ("result", "quotient"):
            return f"{dividend} ÷ {divisor} = ___"
        elif blank_target in ("b", "divisor", "n"):
            return f"{dividend} ÷ ___ = {quotient}"
        else:
            return f"___ ÷ {divisor} = {quotient}"
    
    else:
        # Fallback: use question_text_with_blank or construct from question_text
        return ctx.question_text_with_blank or f"{ctx.question_text} = ___"


def format_cloze(ctx: QuestionContext, rng: random.Random) -> FormattedProblem:
    """
    Format a QuestionContext as a cloze (fill-in-the-blank) problem.

    Respects the 'context' variant in ctx.values or ctx.difficulty_profile:
    - "pure": Shows equation with blank (e.g., "5 + 3 = ___")
    - "word_problem": Shows story with blank (e.g., "Maria has 5 apples and gets 3 more. She has ___ apples.")

    format_data:
        sentence           — the equation/story with ___ in place of the answer
        answer_length_hint — character count of the correct answer
        context            — "pure" or "word_problem"
    """
    values = ctx.values or {}
    
    # Get context variant - check values first, then difficulty_profile
    context_variant = values.get("context") 
    if context_variant is None and ctx.difficulty_profile:
        context_variant = ctx.difficulty_profile.get("context")
    if context_variant is None:
        context_variant = "pure"  # default
    
    # Build sentence based on context
    if context_variant == "word_problem":
        # Use word problem from values (generated by spine) with blank
        # First check if values has a pre-built "question_with_blank" or "question"
        if "question_with_blank" in values:
            sentence = values["question_with_blank"]
        elif ctx.question_text_with_blank:
            sentence = ctx.question_text_with_blank
        else:
            # Fallback: append ___ to question
            sentence = f"{ctx.question_text} ___"
    else:
        # Pure equation: "5 + 3 = ___"
        sentence = _build_equation_sentence(ctx)
    
    answer_str = str(ctx.correct_answer)
    answer_length_hint = len(answer_str)

    format_data = {
        "sentence": sentence,
        "answer_length_hint": answer_length_hint,
        "context": context_variant,
    }

    # Attempt to build MCQ options
    correct = ctx.correct_answer
    candidates = []
    seen = {correct}
    for d in ctx.distractors:
        if d not in seen:
            candidates.append(d)
            seen.add(d)

    if len(candidates) < 3 and isinstance(correct, (int, float)):
        for offset in [-1, 1, 2, -2, 10, -10]:
            if len(candidates) >= 3:
                break
            candidate = correct + offset
            if candidate not in seen:
                candidates.append(candidate)
                seen.add(candidate)

    mcq_options = None
    if len(candidates) > 0:
        distractors = candidates[:3]
        pool = [{"value": correct, "is_correct": True}] + [
            {"value": d, "is_correct": False} for d in distractors
        ]
        pad_index = 1
        while len(pool) < 4:
            if isinstance(correct, (int, float)):
                pad_val = correct + pad_index * 3
            else:
                pad_val = f"{correct} (alt {pad_index})"
            if pad_val not in seen:
                pool.append({"value": pad_val, "is_correct": False})
                seen.add(pad_val)
            pad_index += 1
        
        rng.shuffle(pool)
        keys = ["A", "B", "C", "D"]
        mcq_options = []
        for key, opt in zip(keys, pool):
            mcq_options.append({"key": key, "value": opt["value"], "text": str(opt["value"]), "is_correct": opt["is_correct"]})
            if opt["is_correct"]:
                format_data["correct_key"] = key
        format_data["mcq_options"] = mcq_options

    # Set format properties
    format_type = "mcq" if mcq_options else "cloze"
    answer_collection = "mcq" if mcq_options else "fill_in_blank"

    return FormattedProblem(
        problem_id=f"{ctx.node_id}_{ctx.seed}_cloze",
        node_id=ctx.node_id,
        competency_text=ctx.competency_text,
        grade=ctx.grade,
        seed=ctx.seed,
        question_text=sentence,
        correct_answer=ctx.correct_answer,
        distractors=candidates[:3],
        hints=ctx.hints,
        format=format_type,
        format_data=format_data,
        is_visual=bool(ctx.visual_params),
        visual_type=ctx.visual_type,
        visual_params=ctx.visual_params,
        interaction_mode=None,
        answer_collection=answer_collection,
        difficulty_profile=ctx.difficulty_profile or {},
        difficulty_axes_served=ctx.difficulty_axes_served,
        experience="standard",
        experience_config=None,
        interest_theme=ctx.interest_theme,
        spine_id=ctx.spine_id,
        analytics={
            "time_to_answer_ms": None,
            "trap_triggered": None,
            "is_correct": None,
        },
    )
