"""
test_semantic_leak_guards.py
============================
Semantic-leak prevention is a RENDER-TIME property, not a number-pair property.

A leak occurs when the answer appears verbatim in the *visible* stem more times
than the given (non-answer) operands explain. The same pair (5, 0) renders as a
leak-free "5 - 0 = ___" (blank=result; the visible 5 is an explained given) —
so leaks must be judged on the rendered `FormattedProblem`, using
`given_values` + `blank_target`, exactly as the auditor does
(exhaustive_checklist_auditor.py). They must NOT be prevented by excluding valid
number pairs in the DNA.

This file replaces the previous version, which asserted the WRONG contract: that
the DNAs must never emit a==b / b==0 / factor==1 etc. Those are legitimate
MATATAG problems (subtracting zero, subtracting a number from itself, ×1
identity, doubles) that students must learn. The tests below therefore assert:

  1. The DNAs DO generate the full curriculum space (incl. the old "leak" pairs).
  2. Every rendered problem is leak-free under the auditor's explainable-count
     rule (across formatters), because the formatter reports given_values
     accurately and/or blanks a non-answer slot.
"""

import re

import pytest

from backend.app.services.orchestrator import PracticeOrchestrator
from backend.app.practice_gen.adapter import to_legacy_dict
from tests.exhaustive_checklist_auditor import (
    is_prompt_target_formatter,
    stem_is_prompt_target,
)


# ─── shared render-time leak check (mirrors the auditor) ─────────────────────

def _is_rendered_leak(node_id, profile, formatter, seed):
    """Return (leaked: bool, stem, detail) using the auditor's exact rule."""
    prob = PracticeOrchestrator.generate_problem(
        node_id=node_id, seed=seed, difficulty_profile=dict(profile),
        formatter=formatter, is_lab=False,
    )
    d = to_legacy_dict(prob)
    stem = d.get("stem", "")
    answer = str(d.get("correct_answer"))
    if is_prompt_target_formatter(formatter) or stem_is_prompt_target(stem):
        return False, stem, "carve-out"
    occ = len(re.findall(rf"(?<!\d){re.escape(answer)}(?!\d)", stem))
    given = d.get("given_values") or {}
    explained = sum(1 for v in given.values() if str(v) == answer)
    return (occ > explained), stem, f"occ={occ} explained={explained}"


def _no_rendered_leaks(node_id, profile, formatters, seeds=range(120)):
    offenders = []
    for fmt in formatters:
        for seed in seeds:
            try:
                leaked, stem, detail = _is_rendered_leak(node_id, profile, fmt, seed)
            except Exception:
                continue  # profile/formatter incompatibility is not a leak
            if leaked:
                offenders.append((fmt, stem, detail))
    return offenders


# ─── DNAs generate the full curriculum space (old "leak" pairs included) ─────

class TestDnasGenerateFullSpace:
    def test_subtraction_emits_identity_and_double_pairs(self):
        from backend.app.practice_gen.dna.na.subtraction import generate_params
        seen = set()
        for seed in range(400):
            p = generate_params(grade=1, seed=seed,
                                 difficulty_profile={"regrouping": "none"})
            seen.add((p["a"], p["b"]))
        assert any(b == 0 for _, b in seen), "a-0 (subtract zero) never generated"
        assert any(a == b for a, b in seen), "a-a (result 0) never generated"
        assert any(a == 2 * b and b > 0 for a, b in seen), "a-b==b never generated"

    def test_missing_number_emits_equal_operand_pairs(self):
        from backend.app.practice_gen.dna.na.missing_number import generate_params
        seen = set()
        for seed in range(400):
            p = generate_params(grade=1, seed=seed,
                                 difficulty_profile={"op": "addition_subtraction"})
            seen.add((p.get("a"), p.get("b")))
        assert any(a == b for a, b in seen if a is not None), \
            "a==b never generated by missing_number"


# ─── rendered problems are leak-free (the real contract) ─────────────────────

_TEXTUAL = ["mcq", "cloze", "numeric_input"]


class TestRenderedProblemsAreLeakFree:
    def test_subtraction_node_no_rendered_leaks(self):
        offenders = _no_rendered_leaks(
            "mat_g1_na_q3_0", {"regrouping": "none", "context": "pure"}, _TEXTUAL)
        assert not offenders, f"rendered leaks: {offenders[:5]}"

    def test_subtraction_identity_pairs_render_clean(self):
        # Specifically exercise a-0 and a-a and confirm no leak.
        node = "mat_g1_na_q3_0"
        checked_a0 = checked_aa = False
        for seed in range(400):
            leaked, stem, _ = _is_rendered_leak(
                node, {"regrouping": "none", "context": "pure"}, "cloze", seed)
            if re.search(r"\b(\d+)\s*[-−]\s*0\b", stem):
                assert not leaked, f"a-0 leaked: {stem}"
                checked_a0 = True
            if re.search(r"\b(\d+)\s*[-−]\s*\1\b", stem):
                assert not leaked, f"a-a leaked: {stem}"
                checked_aa = True
        assert checked_a0, "no a-0 rendered to check"
        assert checked_aa, "no a-a rendered to check"
