"""Executable controls for H-04's finite obligation executor."""

from __future__ import annotations

from tests.obligation_executor import (
    CacheResult,
    ExecutionFailure,
    DEFAULT_SEEDS_PER_OBLIGATION,
    SEED_SLOT_SCALARS,
    _base_obligations,
    cache_key_count,
    decode_cache_index,
    difficulty_profile_for,
    experience_values,
    execute_indices,
    finite_obligation_count,
    interest_request_values,
    pr_indices,
    pr_sentinel_indices,
    representative_indices,
    release_receipt_findings,
    represented_execution_count,
    shard_indices,
    stable_seed,
)


def test_current_finite_product_is_the_corrected_reachable_count():
    # Four incompatible peso_money_build routes were removed from production. The
    # manifest must track that executable student-path truth, not an earlier floor.
    #
    # 4269 -> 4277 on 2026-09-19, and the eight are an INCREASE in what production
    # serves, not a re-count of the same tree. `formatter_refused_at_node` read a
    # partially-supported variant bound as a refusal (ALL, not ANY); the orchestrator now
    # narrows such a bound to the formatter-supported subset, so the pair is served
    # instead of raising. Each of the eight was confirmed by EXECUTION before this number
    # was touched -- 5 of 5 seeds each, no exceptions:
    #     mat_g1_na_q3_4 subtraction/number_line_read  x6 (spine x structure)
    #     mat_g2_na_q3_5 division/array_grid_read+set  x2
    # Both competencies name pictorial models explicitly ("using concrete and pictorial
    # models"; "a variety of concrete and pictorial models"), so the old reading was
    # suppressing routes the curriculum requires -- mat_g2_na_q3_5's `objects` capability
    # is a live §6F CONTRADICTED finding for exactly that missing pictorial evidence.
    #
    # 4277 -> 4289 in the same change, via §2B rather than by hand. The ANY reading also
    # made cloze/error_detect/true_false servable on mat_g3_na_q3_1, so
    # `advertised_formatters_are_servable` FAILED naming all three as stale exclusions --
    # the gate doing its job -- and `_generated_formatter_exclusions.py` was REGENERATED
    # with its documented script, never hand-edited. The 12 added routes are that node x
    # those 3 formatters x context x number_type, all narrowed to task_type=zero_identity,
    # which is the only property value those formatters support. Content spot-checked:
    # "6 x 0 = ___" -> 0 and "1 x 9 = ___" -> 9, the zero and identity properties this
    # node's competency names outright.
    #
    # 4289 -> 4281, a DECREASE and an intended one. `mass_capacity` gained a visual
    # formatter (`scale_read`) and FORMATTER_VARIANT_SUPPORT moved `read_measurement`
    # to it, so mat_g3_mg_q2_0 and mat_g3_mg_q2_3 each traded 8 textual routes
    # (mcq+cloze x 4 units) for 4 visual ones. Those textual routes were the
    # UNANSWERABLE items: "What is the mass of the object in g?" with no object drawn
    # and no number in the stem, 20 of 20 seeds per node. Fewer routes, all of them
    # answerable. `_generated_formatter_exclusions.py` was regenerated by its script,
    # which is what narrows those two nodes to scale_read alone.
    assert len(_base_obligations()) == 4281
    assert len(interest_request_values()) == 27
    assert len(experience_values()) == 4
    assert finite_obligation_count() == 462_348
    assert represented_execution_count() == 2_311_740


def test_seed_slots_cover_boundaries_and_extra_interiors():
    assert SEED_SLOT_SCALARS[:3] == (0.0, 0.5, 1.0)
    assert len(SEED_SLOT_SCALARS) == DEFAULT_SEEDS_PER_OBLIGATION


def test_continuous_axes_are_pinned_by_the_seed_slot():
    obligation = next(o for o in _base_obligations()
                      if o.dna == "addition")
    for slot, scalar in enumerate(SEED_SLOT_SCALARS):
        profile = difficulty_profile_for(obligation, slot)
        assert profile["max_sum"] == scalar
        assert profile["number_difficulty"] == scalar


def test_seed_is_stable_and_changes_with_each_execution_coordinate():
    key = _base_obligations()[0].key()
    seed = stable_seed(key, None, 0)
    assert seed == stable_seed(key, None, 0)
    assert len({
        seed,
        stable_seed(key, "bible", 0),
        stable_seed(key, None, 1),
        stable_seed(_base_obligations()[1].key(), None, 0),
    }) == 4


def test_release_shards_are_complete_non_overlapping_and_order_independent():
    total = represented_execution_count() // len(experience_values())
    shards = [shard_indices(i, 6) for i in range(6)]
    assert sum(len(shard) for shard in shards) == total
    assert all(shard.step == 6 and shard.start == i for i, shard in enumerate(shards))
    # Modulo partition: every global index has exactly one owner, irrespective of the
    # order in which shard receipts arrive.
    for index in (0, 1, 5, 6, total // 2, total - 1):
        owners = [i for i, shard in enumerate(shards) if index in shard]
        assert owners == [index % 6]


def test_representative_sample_covers_every_current_finite_dimension():
    indices = representative_indices(1000)
    decoded = [decode_cache_index(index) for index in indices]
    bases = [entry[0] for entry in decoded]
    assert {o.node_id for o in bases} == {o.node_id for o in _base_obligations()}
    assert {o.dna for o in bases} == {o.dna for o in _base_obligations()}
    assert {o.formatter for o in bases} == {o.formatter for o in _base_obligations()}
    assert {entry[1] for entry in decoded} == set(interest_request_values())
    assert {entry[2] for entry in decoded} == set(range(DEFAULT_SEEDS_PER_OBLIGATION))
    # Every cache key executes all four wrappers, so experience is covered by construction.
    assert set(experience_values()) == {
        "hint_gated", "mastery_drill", "scaffolded", "standard"
    }


def test_pr_tier_crosses_each_changed_base_obligation_completely():
    changed = _base_obligations()[0]
    indices = pr_indices([changed.key()])
    matching = [decode_cache_index(index) for index in indices
                if decode_cache_index(index)[0].key() == changed.key()]
    assert len(matching) == len(interest_request_values()) * DEFAULT_SEEDS_PER_OBLIGATION
    assert {(entry[1], entry[2]) for entry in matching} == {
        (interest, slot)
        for interest in interest_request_values()
        for slot in range(DEFAULT_SEEDS_PER_OBLIGATION)
    }


def test_unknown_changed_key_fails_loudly():
    import pytest

    with pytest.raises(ValueError, match="absent from the current manifest"):
        pr_indices(["not|a|live|obligation"])


def test_missing_release_receipts_are_a_blocking_finding(tmp_path):
    findings, summary = release_receipt_findings(tmp_path / "absent-receipts")

    assert summary["status"] == "not_run"
    assert summary["complete"] is False
    assert findings == [
        "no release shard receipts exist; the complete finite sweep is uncertified"
    ]


def test_executor_stops_after_first_failed_obligation(monkeypatch):
    calls = []

    def fake_execute(payload):
        index, _seed_count = payload
        calls.append(index)
        failure = ExecutionFailure(index, 731, "planted", "AssertionError", "boom")
        return CacheResult(index, 0.0, 0, (), (), 0, failure)

    monkeypatch.setattr("tests.obligation_executor._execute_cache_key", fake_execute)
    results, _elapsed = execute_indices(range(5), workers=1)

    assert calls == [0]
    assert len(results) == 1
    assert results[0].failure is not None


# ── the sample's uniformity, which the release budget is multiplied out of ────
# `benchmark()` projects the whole release sweep as
# `elapsed / len(indices) * cache_key_count(...)`, and §11 gates on the two
# `*_within_budget` flags derived from it. A sample that is not uniform over the
# index space makes that gate report "within budget" from a skewed mean.
#
# Measured at sample_size=1000 before 2026-09-16: the stride denominator was
# `sample_size - 1` (999) while only `sample_size - len(sentinels)` = 832 points
# were emitted, so the strided component covered 83.4% of the span and the top two
# deciles held 44 and 11 points against a uniform ~100. H-04's release shards,
# sized from that projection, ran far past it and were killed without a receipt.


def test_the_sample_spans_the_whole_index_space():
    """The defect directly: the strided component stopped at 83.4% of the range."""
    total = cache_key_count(DEFAULT_SEEDS_PER_OBLIGATION)
    sentinels = set(pr_sentinel_indices(DEFAULT_SEEDS_PER_OBLIGATION))
    strided = [i for i in representative_indices(1000) if i not in sentinels]
    covered = max(strided) / (total - 1)
    assert covered > 0.99, (
        f"strided points cover only {covered:.1%} of the cache-key span; the release "
        f"projection is a linear extrapolation of this sample's mean cost"
    )


def test_no_decile_of_the_index_space_is_starved():
    """
    Uniformity, stated as a bound rather than an exact count: sentinels are included
    by contract and they cluster low, so decile 0 runs legitimately heavy. What must
    not recur is a decile the sample barely touches.
    """
    total = cache_key_count(DEFAULT_SEEDS_PER_OBLIGATION)
    indices = representative_indices(1000)
    counts = [0] * 10
    for index in indices:
        counts[min(9, index * 10 // total)] += 1
    assert min(counts) >= 60, (
        f"decile counts {counts} — a decile under 60 of an expected ~100 means the "
        f"projection is extrapolating from a region it barely sampled"
    )


def test_the_sample_is_exactly_the_requested_size_and_deterministic():
    """No truncation of the high tail, no short return, same answer every call."""
    first = representative_indices(1000)
    assert len(first) == len(set(first)) == 1000
    assert first == representative_indices(1000)


def test_every_sentinel_survives_the_top_up():
    """
    The top-up bisects gaps, which must never displace a sentinel: the sentinels are
    the only thing guaranteeing the sample touches each node/DNA/formatter family.
    """
    sentinels = set(pr_sentinel_indices(DEFAULT_SEEDS_PER_OBLIGATION))
    assert sentinels <= set(representative_indices(1000))


def test_a_sample_the_size_of_the_sentinel_set_is_exactly_the_sentinels():
    """The boundary: no strided points to emit, and the stride must not divide by zero."""
    sentinels = pr_sentinel_indices(DEFAULT_SEEDS_PER_OBLIGATION)
    assert representative_indices(len(sentinels)) == sorted(sentinels)
